#!/bin/bash
set -eu

# PREPARATION

# env vars from certbot:
# the hostname that is is validated
challenge_domain="$CERTBOT_DOMAIN"
# the content of the validation challenge
challenge_string="$CERTBOT_VALIDATION"

# our config, the API token for the Hetzner DNS API
api_auth_token=$(cat /etc/hetzner-dns-token)
external_dns_server=8.8.8.8 # google

# check if validation for this hostname was delegated (with a CNAME record)
echo "Validating domain '${challenge_domain}'"
challenge_cname="$(dig +noall +short "_acme-challenge.${CERTBOT_DOMAIN}" | sed 's/\.$//')"
if test -n "$challenge_cname"; then challenge_domain="$challenge_cname"; fi
echo "Using challenge domain '${challenge_domain}'"

# find the id of the "zone" in the DNS console which we need to modify
zone_domain="$challenge_domain"
while test -z "${zone_id:-}" ; do
  zone_id=$(curl --silent -H "Auth-API-Token: ${api_auth_token}" \
    "https://dns.hetzner.com/api/v1/zones?search_name=${zone_domain}" | \
    jq ".\"zones\"[] | select(.name == \"${zone_domain}\") | .id" 2>/dev/null | tr -d '"')
  if ! test -z "$zone_id"; then
    echo "Using DNS zone '${zone_domain}' with id '${zone_id}"
    break
  else
    # if not found yet, continue looking with 1 less sudomain
    zone_domain="$(echo "$zone_domain" | cut -s -d'.' -f 2-)"
  fi
  # fail when search is exhausted (no more subdomains to remove)
  if test -z "$zone_domain"; then
    echo "ERROR: could not find DNS zone!" >&2
    exit 1
  fi
done

# COMMANDS

auth(){
  # clenaup any old records
  cleanup

  # create the challenge DNS record
  curl --silent -X "POST" "https://dns.hetzner.com/api/v1/records" \
    -H 'Content-Type: application/json' \
    -H "Auth-API-Token: ${api_auth_token}" \
    -d "{ \"value\": \"${challenge_string}\", \"ttl\": 30, \"type\": \"TXT\", \"name\": \"${challenge_domain}.\", \"zone_id\": \"${zone_id}\" }"

  # wait until we can observe the correct value in the DNS record
  printf "waiting for DNS record to be visible on external DNS ($external_dns_server)..." && \
  while ! test "\"${challenge_string}\"" = "$(dig @"$external_dns_server" -t txt +short "${challenge_domain}")"; do printf '.'; sleep 5; done
  echo " OK!"
}

cleanup() {
  # find and delete the validation record (possibly several)
  record_ids=$(curl --silent -H "Auth-API-Token: ${api_auth_token}" \
          "https://dns.hetzner.com/api/v1/records?zone_id=$zone_id" | \
        jq ".\"records\"[] | select(.name == \"${challenge_domain}.\") | .id" 2>/dev/null | tr -d '"')

  for record_id in $record_ids; do
    curl --silent -H "Auth-API-Token: ${api_auth_token}" \
      -X "DELETE" "https://dns.hetzner.com/api/v1/records/${record_id}"
  done
}

# RUN COMMAND

if [[ $1 =~ ^(auth|cleanup)$ ]]; then
  "$1"
else
  echo "Invalid command `$1`, valid commands are `auth` and `cleanup`" >&2
  exit 1
fi